# config file
development:
  remote_server: '192.168.1.110'
  remote_port: 6600

test:
  remote_server: '192.168.1.110'
  remote_port: 6600

production:
  remote_server: '192.168.1.110'
  remote_port: 6600
