# config file
development:
  remote_server: 'localhost'
  remote_port: 6600
  
test:
  remote_server: '192.168.0.2'
  remote_port: 6600

production:
  remote_server: '192.168.0.2'
  remote_port: 6600
